### ISSUE TITLE
readline quoting doesn't escape single quote

### ISSUE THREAD

**Issue by TobyGoodwin** [rakitzis/rc#1]
Reported by @siebenmann and @jwilk

**Comment by TobyGoodwin** [comment]
When I was looking into this, I made [some notes](http://tobold.org/article/rc-notes) I'm not sure which version of readline it was, but presumably something less than 7.0 which has recently been released. It might be checking again to see if the situation has changed.

However, it appears that we have a regression. According to the notes, in `1.7.2` completion **did** work properly for filenames containing quotes, providing there are no decision points beyond the quote. This is no longer the case.

**Comment by xyb3rt** [comment]
Fixed in commit cf3c76f57f520fb656a101baff501b44eb42ca77.
