### ISSUE TITLE
here strings should automatically include an extra newline

### ISSUE THREAD

**Issue by TobyGoodwin** [rakitzis/rc#10]
[This issue was raised as a comment by @nobrowser  on the initial github commit of rc-1.4. That didn't seem a very useful place for it, and is an enormously long page. I've moved it here for ease of discussion.]

Hi, if I am not mistaken the implication of this code is that here-strings are handled exactly the same as here-docs. In particular that means there is no automatic terminating newline for here-strings. This is a problem, because you cannot do something like:

    result=`{bc <<< 1 + 1 }

to work around rc's complete lack of arithmetic. bc barfs on input that is not newline terminated.

Bash (and I believe ksh) automatically append a newline to here-strings. Would it be possible to do this in rc, or would a patch implementing this change be considered? It would break backward compatibility, unfortunately.

**Comment by TobyGoodwin** [comment]
Note that only the first string after `<<<` forms the here string. Your example should read:

    result = `{ bc <<< '1 + 1' }

which as you say is a syntax error in `bc`.

If you want a newline, simply write one:

    result = `{ bc <<< '1 + 1
    ' }

or

    nl = '
    '
    result = `{ bc <<< '1 + 1' ^ $nl }

or use the `echo` builtin, which *does* automatically add a newline

    result = `{ echo 1 + 1 | bc }

Or define a function that uses one of the above techniques

    fn calc { echo $* | bc }
    result = `{ calc 1 + 1 }

**Comment by TobyGoodwin** [comment]
[ @borkovic added the following comment, again as a comment to the initial commit ]

I am sure arithmetic capability in rc has been discussed before. Maybe it is time to open it for discussion again?
(Creating a subprocess just to increment a number or compare two numbers seems wasteful.)

**Comment by TobyGoodwin** [comment]
Yes, it has been discussed before.

One obvious objection, beyond rc's proud minimalism: how much arithmetic would you add? Just small whole numbers, addition and multiplication? Bignums? Integers and subtraction? Division and rationals? Floating point? Trigonometrical functions? Complex numbers? Polynomials? Matrices?

I'm being slightly facetious, but the point is a good one. By keeping *all* arithmetic out of rc, you can choose the right tool for the job: `expr` and `test` for simple counting, `bc` for arbitrary precision. Or you could use something heavyweight: I'd probably fire up `ghc -e` if I wanted to calculate with polynomials, or `R -e` for statistics. This is the essence of the tools approach.

And my riposte to *seems wasteful* is Dan Bernstein's: profile, don't speculate! Unless you can demonstrate a real example of code that would run significantly faster by adding features to rc, you have no performance case for requesting such features.

**Comment by nobrowser** [comment]
*expr* ??  Really?

As far as I am concerned, the whole point of here strings is to avoid recourse to echo or printf.  Is there a use case for here strings that is *not* covered by echo?  If not maybe should should consider removing here strings.  (I can be facetious, too) :-)

**Comment by TobyGoodwin** [comment]
As the man page says, here strings were introduced by Byron to "facilitate exporting of functions with here documents". (Exercise: what exactly is hard about here documents?) So using here strings is not portable (to Duff's rc), if you care about that.

The fact that *echo* is a builtin is described as a bug in the man page, although there are no plans to change it. I think you're right, that here strings and builtin echo are interchangeable, although if we were to lose here strings `configure --disable-builtin-echo` would have to go too.
