### ISSUE TITLE
Combining assignment and break

### ISSUE THREAD

**Issue by borkovic** [rakitzis/rc#11]
In the following script the error "break outside of loop" is printed. As far as I can tell, this behavior is consistent with exception stack handling in *rc_raise*. Is this behavior expected?

```
github/rakitzis/rc/ $ cat brk

tf=true
while ($t) {
    tf=false
    echo before break
    x=3 {
        break
    }
    echo after break
}

github/rakitzis/rc/ $ ./rc brk
before break
rc: line 10: break outside of loop
github/rakitzis/rc/ $ 
```

If assignment `x=3` is removed, `break` executes without issues. 

```
github/rakitzis/rc/ $ cat brk2

tf=true
while ($t) {
    tf=false
    echo before break
    {
        break
    }
    echo after break
}

github/rakitzis/rc/ $ ./rc brk2
before break
github/rakitzis/rc/ $ 
```

**Comment by rakitzis** [comment]
Whew that is a crazy corner of the language. The root of the bug is that break is a builtin and not part of the grammar. I don't remember how/when it made it it into rc. It's not part of plan9's rc. So you are running the break builtin in a subcommand ( x=3{stuff} ) and that is not working as you expect it to.

**Comment by borkovic** [comment]
The same issue happens with `.` (dot). Any command that adds something to the exception stack would exhibit the same behavior.
If I understand you correctly, having `break` in the grammar would avoid the problem by creating a different parse tree to walk. Do you think `rc_raise` could be enhanced to handle this and other exceptions (when reasonable)?

```
github/rakitzis/rc/ $ cat brk3

tf=true
while ($t) {
    tf=false
    echo before break in dot
    . ./brk4
    echo after break in dot
}

github/rakitzis/rc/ $ cat brk4
break

github/rakitzis/rc/ $ rc brk3
before break in dot
rc: line 1: break outside of loop
github/rakitzis/rc/ $ 
```

**Comment by rakitzis** [comment]
If break is put in the grammar rc_raise would probably need no changes -- you would get syntax errors when running break inside dot, for example.

**Comment by borkovic** [comment]
Would you mind describing how having `break` in the grammar resolves the issue?
```
while (cond1) {
  x=1 {  if (cond2) {  if (cond3)  break }
      }
}
```
Presumably, in the above example `break` would be a node in the tree under both `ifs`. Would the execution of the `break` node apply a mechanism different than current exception unwinding?

**Comment by rakitzis** [comment]
First of all: I'm speaking hypothetically about altering the grammar. But if it were in the grammar, the thing you typed there would not parse. You would get something like "syntax error: break inside subcommand". It would never make it to the AST, and there would be no exception to unwind.

As far as the example you gave, it may be reasonable to figure out how to make break do the "right thing". But notice that it becomes instantly unreasonable once the command is executing in a subshell (e.g., as part of a pipeline or with an `@` directive). This is all I meant.

I haven't thought enough about how to fix this but I would like to use the principle of "least surprise" here. But for the particular example you typed I agree it looks wrong if break does not break the loop.

**Comment by borkovic** [comment]
* I see - the grammar would not allow the construct in the first place. I was wondering how the construct would be executed.
* I agree that `break` out of a subshell would be very unreasonable.
* The "least surprise" principle is good.  Deciding which combinations of exceptions are allowed during `break` unwinding would be tricky, especially if the legality is order dependent. As for my example, the local variables can be "declared" outside of the loop.

**Comment by muennich** [comment]
Is there any reason not to support breaking a loop from within such a variable block? I would not expect rc to support break from within a dotted file or a subshell. But it was a big surprise to me, that break did not work inside a compound statement with local variables. In my opinion, the current situation does not adhere to the "least surprise" principle.
