### ISSUE TITLE
How to get colours in the prompt?

### ISSUE THREAD

**Issue by amarakon** [rakitzis/rc#111]
I’m trying to get colours in my prompt but I’m not sure what the right way to do it is. Currently, I’m capturing the output of `/bin/echo -e` and using ANSI escape sequences, because the builtin `echo` doesn’t support the `-e` flag.

```rc
fn cecho {
	if (~ $3 ()) {
		colour = ''
		output = $2
	} else {
		colour = ';'$2
		output = $3
	}
	/bin/echo -e '\e['$1$colour'm'$output'\e[0m'
}

fn prompt {
	if (~ $status 0) {
		Status = ''
	} else {
		Status = `{cecho 1 31 ' ['$status]}
		#Status = ' ['$status]
	}

	me = `whoami
	if (~ $me root) {
		user_colour = 31
	} else {
		user_colour = 32
	}

	user = `{cecho 1 $user_colour $me}
	at = `{cecho 1 @}
	host = `{cecho 1 35 `hostname}
	dir = `{cecho 1 34 `pwd}
	end = `{cecho 1 ';'}

	prompt = $user$at$host' '$dir$end' '
	#prompt = `whoami@`hostname' '`pwd$Status'; '
}
```

However, my workaround causes the text I write into the prompt to overwrite the prompt itself. To see what I mean, look at the following screenshot where I wrote `ls downloads/`.

![rc-prompt](https://github.com/user-attachments/assets/feb5b3c2-810d-490d-9f70-43a3eda4a38d)

**Comment by rakitzis** [comment]
MacOS doesn't have "echo -e", I used

```
esc=`{printf '\033'}
```

to capture the ESC (decimal 27, octal 33) and replacing `$esc` throughout your code sample seems to yield working code.

**Comment by rakitzis** [comment]
In any case this is likely not a bug with rc but most likely with your terminal settings or use of escape codes. I haven't worked through it.

**Comment by jpco** [comment]
If you're using readline, it expects `\001` and `\002` around any sequences of non-printable characters.  Does wrapping the color sequences in those characters (either with `echo -e` or `printf`) make things work correctly?  Something like this?
```
/bin/echo -e '\001\e['$1$colour'm\002'$output'\001\e[0m\002'
```

**Comment by amarakon** [comment]
Thank you for your help! After reading your comments and adapting my code, I was able to fix the issue. Indeed, the issue is caused by not wrapping the string with `\001` and `\002`. Also, this time I’m using `printf` instead of `/bin/echo -e` because I think it looks cleaner. I didn’t know that escape sequences also work with `printf`. This is my updated code:

```rc
fn esc {
	printf '\001\e['^$1^'m\002'^$2^'\001\e[0m\002'
}

fn prompt {
	if (~ $status 0) {
		Status = ''
	} else {
		Status = ' '^`{esc '1;31' '['$status]}
	}

	me = `whoami
	if (~ $me root) {
		user_colour = 31
	} else {
		user_colour = 32
	}

	user = `{esc '1;'^$user_colour $me}
	host = `{esc '1;35' `hostname}
	dir = `{esc '1;34' `pwd}

	prompt = $user@$host^' '^$dir^$Status^'; '
}
```
