### ISSUE TITLE
chldign is an executable and is included in the repository

### ISSUE THREAD

**Issue by borkovic** [rakitzis/rc#12]
File  *chldign* is an executable file and is included in  *ratkitzis/rc*. Should it be included in the repository?

```
chldign     release: rc-1.7.2	5 months ago
chldign.c	release: rc-1.7.2	5 months ago
```

File description as *executable* at https://github.com/rakitzis/rc/blob/master/chldign:

rc/chldign
@TobyGoodwin TobyGoodwin release: rc-1.7.2                          a8699a5  on May 16
1 contributor
RawHistory Executable File  4.02 KB

**Comment by TobyGoodwin** [comment]
Nope. Obviously not!

And nor should chldign.c, which isn't used anywhere. (It was obviously part of a feature test at some point, but apparently one we no longer need.)

Thanks for the eagle eyes @borkovic !
