### ISSUE TITLE
compatibility with Plan 9 rc: `flag`

### ISSUE THREAD

**Issue by GReagle** [rakitzis/rc#20]
Could the absence of the `flag` built-in command (which is in Duff's rc) be noted in the Incompatibilities section of the man page, or could `flag` be implemented in this version of rc?  Thanks.

**Comment by TobyGoodwin** [comment]
Sorry @GReagle that it's taken me so long to do anything with this.

I've just pushed an implementation of `flag`. I haven't gone out of my way to look at what flags the Duff `rc` implements, just done sensible things with our flags. So this may need a bit of tweaking to be really useful to sharing scripts.

Let me know what you think.
