### ISSUE TITLE
Support for linenoise

### ISSUE THREAD

**Issue by v217** [rakitzis/rc#22]
The minimal readline alternative written by the Redis inventor

https://github.com/antirez/linenoise

seems to offer all rc-shell needs.

**Comment by TobyGoodwin** [comment]
Uh, yeah, I started looking at this, but got distracted by another project, sorry. Hope to get back to it soon

**Comment by CasperVector** [comment]
I compared linenoise/linenoise-ng with editline, and find the latter to be smaller (speaking of static libraries) and [seemingly](https://github.com/NixOS/nix/issues/2014) less buggy.  Of course, your mileage may vary.

**Comment by xyb3rt** [comment]
Closing, because we'd have to include linenoise's source files and the project has a lot of open issues and does not properly support non-ASCII input.
