### ISSUE TITLE
Using ${} instead of `{} for command substitution

### ISSUE THREAD

**Issue by v217** [rakitzis/rc#23]
Since you already improved upon the original rc-shell, I was wondering what you think about this idea about backquoting for command substitution:
Using ${} instead of `{}.

The advantages are:
- It's closer to the Bourne Posix shell.
- There's one reserved character less.
- It's more readable without syntax-highlighting.
- It's trivial to convert older scripts to the new syntax.

The disadvantages are maybe:
- You always have to use braces.
- I haven't thoroughly checked if this results in any syntax ambiguity? - But I don't think so.

**Comment by TobyGoodwin** [comment]
My initial reaction is that this is a splendid idea! When I'm in a bourne shell these days, I always use `$()` over `` ` ` ``, and I find it something of a mental jump to go back to `` `{} `` in rc.

Assuming there are no syntax issues, I'd be in favour of adding this syntax. (Unfortunately, I don't think removing `` `{} `` is feasible, especially since some users are clamouring for more compatibility with the Plan 9 rc.)

@rakitzis any thoughts?

**Comment by v217** [comment]
One option would be to implement a flag for backwards portability mode. So future modifications or additions would be worry free.

**Comment by rakitzis** [comment]
Interesting problem. Ironically this would have been a ksh feature, probably, long before it was a POSIX feature, and rc predates POSIX. But I also bet `{} was inspired by ksh $() so what goes around comes around.

I don't oppose this with the provisos: (1) no way is this a breaking syntax change, (2) no way is there a compatibility flag. Both forms would have to work going forward.

**Comment by borkovic** [comment]
Do we have corresponding syntax for backquote substitution with `$ifs` override?
Also, how did you highlight backquotes?

**Comment by nobrowser** [comment]
By the way, Emacs (up to 24.5) has completely broken highlighting for `{} .  It seems to be looking for the closing ` which never comes ...
If this proposal is adopted, I can at last start writing rc scripts, the one religiously correct editor being available for the purpose :-)

**Comment by rakitzis** [comment]
Ironic that the 10kloc C program would need to be bent to the will of the Turing-complete editor with full Lisp ecosystem built in.

**Comment by TobyGoodwin** [comment]
I've gone off this idea.
