### ISSUE TITLE
Lack of `continue`

### ISSUE THREAD

**Issue by CasperVector** [rakitzis/rc#25]
`return` and `break` have been reintroduced into this neat `rc` implementation.
May I request to also add `continue`?  This can be really helpful for some constructs.

**Comment by TobyGoodwin** [comment]
Thanks for the input. Do you have a short yet compelling example? :smile:

Offhand, it looks to me like

    while (condition) {
        ... stuff ...
        if (something)
            continue;
        .... more stuff ..
    }

can always be replaced by

    while (condition) {
        ... stuff ...
        if (!something) {
            ... more stuff ...
        }
    }

**Comment by CasperVector** [comment]
```
loop {
    stuff1 ...
    cond1 || continue
    stuff2 ...
    cond2 || continue
    ...
}
```
(Similar constructs also happen with `return` and `break` :)

**Comment by borkovic** [comment]
Two reasons I'd vote to add `continue`:
* From Tom Duff's paper: "Where Bourne's syntax draws from Algol 68, rc's is based on C or Awk."
* It is true that both `break` and `continue` can be replaced by  `ifs()`; but `continue` can help reduce excessive indentation.

I have an implementation of `continue` in my repository. If there is a consensus for adding it, I'd be glad to post it for a pull.

**Comment by TobyGoodwin** [comment]
@borkovic I'd be very interested to see your implementaton. Can you turn it into a pull request?

**Comment by borkovic** [comment]
I am out of town. I'll try to do it over the weekend.

**Comment by TobyGoodwin** [comment]
Thanks, looks great! (I particularly like the new `assert()` in `unexcept()`)
I've pushed a branch called `continue` to the main github repo, in case other people want to play with it. I'll merge this into `master` in the next few days unless anyone objects.

**Comment by borkovic** [comment]
Glad to contribute.

Interesting that you like assert() in unexcept(): I was not sure whether to
make 'continue' change alone or to include assert()+unexcept() as well.

**Comment by TobyGoodwin** [comment]
merged
