### ISSUE TITLE
reproducible build - don't use date in configure.ac

### ISSUE THREAD

**Issue by RamKromberg** [rakitzis/rc#26]
While packaging rc for nixpkgs (https://github.com/NixOS/nixpkgs/pull/17947/), _configure.ac_  was modified by removing the date invocation (https://github.com/rakitzis/rc/blob/master/configure.ac#L5) to make the build reproducible.

Btw, my ```.rcrc``` has a little trick in it to change the window's title so not having the path in the prompt is less bothersome:
```
umask 022
path=(/bin /usr/bin /run/current-system/sw/bin)
history=$home/.rc_history
hostname=`hostname
username=$USER

fn getPwd {
        echo `pwd | sed 's,^' ^ $home ^ '*,~,g'
}

fn prompt {
        label=$username ^ $hostname ^ ':' ^ `getPwd
        echo $label | awk '{printf("\033];%s\007", $0);}' >/dev/tty
        #echo -n '[' ^ $label ^ ']'
}
```
I'm considering writing a _pwd_ builtin to get rid of the _sed_ and _pwd_ invocations in _addon.c_.

**Comment by rakitzis** [comment]
My inner optimizer would avoid forking in fn prompt, probably irrelevant these days, but hey:

```
fn cd {
        builtin cd $*
        title
}
fn title {
        pwd=`` ($nl) {pwd|sed s,$h,'$'h,}
        hostname=`hostname
        if (~ $hostname *MacBook*)  {
                echo -n $ctl$pwd$bel
        } else {
                echo -n $ctl$hostname':'$pwd$bel
        }
}
```

where `ctl = $esc ^ ']0;'`

**Comment by TobyGoodwin** [comment]
Ah. The RELDATE idea dates back to when nobody but me was expected to run auto^(make conf), and the release date was frozen at the time of, errm, a release. I'm happy to get rid of it.

I do rather like the idea of having something that exactly pinpoints which version of the code you have. What would you think of burning the output of `git describe` into the version string?

**Comment by RamKromberg** [comment]
@TobyGoodwin As long as it doesn't change between builds, it works fine :)

@rakitzis why is ```hostname=`hostname``` in the title function?

Also, I didn't have the nerve to mention it, but with my efficiency cast in doubt, I'm compelled to note I actually use a hex edited version of the above with 1b hex and 07 hex manually :D
```
       0     75 6d 61 73 6b 20 30 32  32 20 0a 70 61 74 68 3d  28 2f 62 69 6e 20 2f 75  73 72 2f 62 69 6e 20 2f  72 75 6e   umask 022 .path=(/bin /usr/bin /run
      23     2f 63 75 72 72 65 6e 74  2d 73 79 73 74 65 6d 2f  73 77 2f 62 69 6e 29 0a  68 69 73 74 6f 72 79 3d  24 68 6f   /current-system/sw/bin).history=$ho
      46     6d 65 2f 2e 72 63 5f 68  69 73 74 6f 72 79 0a 68  6f 73 74 6e 61 6d 65 3d  60 68 6f 73 74 6e 61 6d  65 0a 75   me/.rc_history.hostname=`hostname.u
      69     73 65 72 6e 61 6d 65 3d  24 55 53 45 52 0a 0a 66  6e 20 67 65 74 50 77 64  20 7b 0a 09 65 63 68 6f  20 60 70   sername=$USER..fn getPwd {..echo `p
      8C     77 64 20 7c 20 73 65 64  20 27 73 2c 5e 27 20 5e  20 24 68 6f 6d 65 20 5e  20 27 2a 2c 7e 2c 67 27  0a 7d 0a   wd | sed 's,^' ^ $home ^ '*,~,g'.}.
      AF     0a 66 6e 20 70 72 6f 6d  70 74 20 7b 0a 09 6c 61  62 65 6c 3d 24 75 73 65  72 6e 61 6d 65 20 5e 20  24 68 6f   .fn prompt {..label=$username ^ $ho
      D2     73 74 6e 61 6d 65 20 5e  20 27 3a 27 20 5e 20 60  67 65 74 50 77 64 0a 09  65 63 68 6f 20 1b 20 5e  20 27 5d   stname ^ ':' ^ `getPwd..echo . ^ ']
      F5     3b 27 20 5e 20 24 6c 61  62 65 6c 20 5e 20 07 20  3e 2f 64 65 76 2f 74 74  79 0a 09 23 65 63 68 6f  20 2d 6e   ;' ^ $label ^ . >/dev/tty..#echo -n
     118     20 27 5b 27 20 5e 20 24  6c 61 62 65 6c 20 5e 20  27 5d 27 0a 7d 0a                                             '[' ^ $label ^ ']'.}.
```

So I don't actually use _printf_...

**Comment by rakitzis** [comment]
Don't remember. Bit rot probably!

**Comment by rakitzis** [comment]
I guess it caches the result. Once upon a time that sort of thing mattered.

**Comment by RamKromberg** [comment]
It still matters... Otherwise, why would I want to put it outside the loop to save up on an invocation? :)

**Comment by RamKromberg** [comment]
@TobyGoodwin anyhow, since you're aware of the problem, I'll close the issue.

Thanks!

**Comment by TobyGoodwin** [comment]
proposed replacement of the date with `$(git describe)` is in commit 89f1e1b

btw, thanks for supporting rc in NixOS (which i keep meaning to find time to have a play with...); let me know if there's anything else i can do to make that simpler for you!

**Comment by RamKromberg** [comment]
@TobyGoodwin Yeah this looks good to me :) 

As for the nix support, it's more like Arch AUR rather then Debian in nix* so there's really not much in the way of "official support" to thank for :) You push a commit. It's reviewed at technical grounds. They tell you to fix this, or change that... And you're done.

Only exception might be unusual licenses, very large packages or closed source... But I've seen a few of those.

Still, you're welcomed non-the-less :D

p.s. There's an interesting technical aspect to nix that is relevant for rc: The default user and system environment doesn't necessitate bash compatibility. Packages are built and linked against each other directly so you can use a shell like rc without breaking half your other packages.

If that hasn't picked your interest, NixOS has a stable release coming up pretty soon. The scheduled freeze for 16.09 is for the end of August. rc already went from master to unstable-small which hopefully means it will make it in time for the release. So, rc will be available with a ```nix-env -iA rc``` invocation and nothing else :)

*Have a look at the maintainers list here: https://github.com/NixOS/nixpkgs/blob/master/lib/maintainers.nix . Pretty liberal looking to me :)
