### ISSUE TITLE
Generalized conditional options for the Bourne/rc shell and tools:

### ISSUE THREAD

**Issue by v217** [rakitzis/rc#28]
The shell has already wildcard expansions - a conditional option for filename-arguments.
Why not generalize this ability to filter/pattern-match every option?

```
ls *.txt
file1.txt
file2.txt

ls -s *.txt      # prints size
11  file1.txt
34  file2.txt

ls -s +20 *.txt
file2.txt

ls -s -s +20 *.txt
34  file2.txt
```

Now find can do this but for ls you need awk or some other workaround.
This seems to be mostly backwards compatible.

**Comment by v217** [comment]
I had to share this, and since this is the shell where innovation happens, I posted this idea here. Just in case anybody wants to rewrite everything from scratch!

**Comment by rakitzis** [comment]
I hate to burst your bubble, because I love innovation, but rc froze for all intents and purposes in 1992 or 1993. That was 25 years ago.
