### ISSUE TITLE
RFE: Make unquoted = in command arguments not be an error

### ISSUE THREAD

**Issue by siebenmann** [rakitzis/rc#29]
My single largest pain point with using rc on Unix is the steadily increasing usage of `=` in command lines, for example with commands that have command line switches of the form `somecmd --someop=foo`. This is currently a syntax error in rc, which means that I have to quote those arguments every time I want to run such a command (and forgetting to do so gets me an error message).

A change to accept `=` here would be backwards compatible with existing working rc scripts and usage; the only change would be that previously invalid input is now accepted. It would create a divergence from the original Bell Labs rc, but Bell Labs had a fix for the problem that this version of rc doesn't (they changed commands like `dd` to not use `=`), so my view is that this is an acceptable compromise.

@muennich carries a commit that makes this change in his rc tree and in light testing so far it appears to work correctly for me. I don't know if it's suitable for cherry-picking directly.

**Comment by rakitzis** [comment]
Totally agree here. Single biggest "bug" in rc.

**Comment by rakitzis** [comment]
It's commit 3f9d6e31f316925201a3e84fd3e7ecbc3b2d231f, it passes trip.rc in my environment, I'd say it's worth folding in!

**Comment by muennich** [comment]
I've been using this commit for months without any problems. I've just created a branch with just this commit that can be merged into your master: https://github.com/muennich/rc/tree/unquoted-equals

**Comment by rakitzis** [comment]
Thanks! I'll let Toby control how the merge happens.

**Comment by TobyGoodwin** [comment]
This looks awesome! Currently on a branch called `equals` and I'll be putting it through its paces. Thanks very much @muennich and @siebenmann !

**Comment by borkovic** [comment]
Do we need a test for this feature in trip.rc?

**Comment by rakitzis** [comment]
Insofar as trip.rc functions as a code coverage suite, a few test cases would be good to have.

**Comment by TobyGoodwin** [comment]
This is now on the master branch, including some simple tests. I'll wrap this up into a 1.8 release in the near future.
