### ISSUE TITLE
try readline ~expansion

### ISSUE THREAD

**Issue by TobyGoodwin** [rakitzis/rc#3]
noticed in passing that readline filename completion can do ~ expansion - be interesting to try this, since ~ expansion is one of those things people ask for from time to time

**Comment by muennich** [comment]
I have implemented tilde expansion in my fork with commit 0924921e. Before doing so, I've used readline's tab-completion to expand the tildes while typing, but forgot to hit tab way too often. My muscle memory depends on the shell to do tilde expansion.

BTW, getting readline to do the expansion via tab-completion requires adding this line to `~/.inputrc`:

    set expand-tilde on

**Comment by TobyGoodwin** [comment]
thanks for the comment, and the patch

i won't be accepting the ~ expansion patch, sorry: we have  a long history of resisting creeping featurism in rc :)

**Comment by muennich** [comment]
That's totally ok with me; I knew the chances for accepting the patch were very low so that I didn't bother to open a pull request but simply mentioned it here for others, who might want to use it.

Thanks for maintaining rc and happy holidays.

**Comment by TobyGoodwin** [comment]
readline's tilde expansion is now 250c8ad mentioned in the man page

**Comment by leorosa** [comment]
Would you consider to also mention the "M-_" keybind from readline? It is very useful for those who use bash' "!$" to call the last argument from the last command...
