### ISSUE TITLE
After syntax error the value of $status is 0

### ISSUE THREAD

**Issue by borkovic** [rakitzis/rc#30]
After syntax error the value of the variable `$status` is 0. Is this behavior expected?

```
; if (true) }
rc: syntax error
; echo $status
0
; )
rc: syntax error
; echo $status
0
```

In bash after syntax error the value of the variable `$?` is 2.

```
$ )
bash: syntax error near unexpected token `)'
$ echo $?
2
```

**Comment by borkovic** [comment]
Status after `Ctrl-C` is also handled differently in `rc` and in `bash`. In `rc` `$status` is 0
```
; echo $status
0
; ^C
; echo $status
0
```

In `bash` status is non-zero.
```
$ echo $?
0
$ ^C
$ echo $?
130
```

**Comment by rakitzis** [comment]
This was a deliberate choice but I don't remember the rationale. Possibly that an interactive shell should not alter `$status` for a syntax error.

`rc -c if` returns a status 1 as you would expect.

What is the use of setting `$status` after hitting C-c in the terminal?

**Comment by borkovic** [comment]
I was looking at places where `rc_raise(eError)` was called rather than `rc_error()` and saw it in `sigint()`. I was curious and tried Ctrl-C.
