### ISSUE TITLE
Discrepancy between if and if/else -- assignment in front of brace causes syntax error in the latter ony

### ISSUE THREAD

**Issue by borkovic** [rakitzis/rc#31]
I notice the following discrepancy between `if` and `if/else`.

(i) An assignment is allowed between `if (cond)` and `if` brace when `if` has no `else`:

```
$ cat i
if (true) a=xxx { echo $a }
$ rc < i
xxx
```

(ii) An assignment in the same location for an `if/else` combination causes a syntax error:

```
$ cat ie2
if (true) a=xxx { echo $a } else { echo $b }
$ rc < ie2
rc: line 1: syntax error near else
```

The cause seems to be that the `brace` variant of `iftail` does not have optional assignment at the beginning. I believe this is just a corner case, and I only wanted to record the issue.

**Comment by TobyGoodwin** [comment]
Interesting.
It seems a pity not to accept the syntax—it appears unambiguous. However, a few minutes of poking at `parse.y` has landed me in a morass of s/r and r/r conflicts. I'm too tired (and my `yacc` theory is too rusty) to see the way out at the moment.
If anybody felt moved to supply a patch / pull request... :-) we probably want to handle redirections in this position too.

**Comment by TobyGoodwin** [comment]
That's fantastic! I'm glad you found a solution that allows any `cmd` - my fumbling attempts had started by duplicating the pre-assignment rules into `iftail`
