### ISSUE TITLE
rc with readline sometimes doesn't notice terminal window resizing

### ISSUE THREAD

**Issue by siebenmann** [rakitzis/rc#32]
If you compile rc with readline support, run a program, and resize the terminal window while the program is running, rc still thinks the window has its old size when the program exits. The result is that readline's line display and line editing can be mangled (how exactly it's mangled depends on whether you made the window wider or narrower).

Based on the documentation, reading the readline source (thanks, readline), and some testing, it appears sufficient to call `rl_initialize()` in `edit_begin()` and then call `rl_reset_screen_size()` in `edit_alloc()` immediately before calling `readline()` itself. However, I may be missing some subtle issue here.

**Comment by TobyGoodwin** [comment]
Thanks! I've bumped into this problem often enough, but I confess I wrote it off as just one of those things.
I've applied the solution you suggest in dc80ccac672785085df2fe20cd3a2a2198f6decb
