### ISSUE TITLE
Inconsistency in output redirection

### ISSUE THREAD

**Issue by CasperVector** [rakitzis/rc#33]
As the title:
```
; ls 0 >[2=1] | sed 's/0/1/'
ls: 1: No such file or directory
; >[2=1] ls 0 | sed 's/0/1/'         
ls: 0: No such file or directory
```

**Comment by CasperVector** [comment]
As a side note, this seems to be consistent with the behaviour of plan9port `rc`, but I personally think the behaviour itself is incorrect.

**Comment by rakitzis** [comment]
I'd have to agree. Not looking at the source at the moment but it seems like an interesting bug. Presumably this is a feature of the grammar, the second redirection applies to the pipe as a whole. Not intuitive.

```
; {>[2=1] ls 0} | sed s/0/1/
```

is what you expect.

**Comment by CasperVector** [comment]
I also consider the grammar to be the root cause.  I think it's worth modifying the grammar spec (if the modification is reasonably simple) to avoid this behaviour, even if that introduces yet another incompatibility to plan9port `rc`...

**Comment by TobyGoodwin** [comment]
It's a simple enough fix, just make the precedence of a prefix redir higher than pipe. d2a398257626faf73fd7a5326b31bbc3f613e3da 
Took me a little while to get there though... I've spent most of the last 10 years playing with [PEGs](https://paccrat.org/) and my CFG / LALR(1) / yacc skills are a little rusty!
I don't have a Duff rc to hand, but I can confirm that the original `rc` grammar as published in the Tenth Edition manuals has the same too-low precedence for a prefix redirection.

**Comment by CasperVector** [comment]
Many thanks :)
