### ISSUE TITLE
When test_cmd returns false the second time in 'while(test_cmd)'  'rc -e' exits

### ISSUE THREAD

**Issue by borkovic** [rakitzis/rc#34]
When `rc -e` is invoked, and the `while()` condition becomes false the **second** time, rc exits (case YYY). If the condition is false the first time (case ZZZ), rc does not exit (but does not enter the loop, as expected).
According to the man page, the YYY behavior seems incorrect.
```
; ./rc -c 'echo $version'
1.7.4 $Release: @(#)rc 1.7.4 rc-clone-2015-Jun-20-492-g250c8ad $
$ ./rc -e
; fn sigexit { echo exiting }
; b=true; while($b) { b=false } ; echo YYY
exiting
$ ./rc -e
; b=false; while($b) { b=true }; echo ZZZ
ZZZ
; exit
exiting
$
```
It does seem that the code for `case nWhile:`  in `walk.c:walk()` sets cond to true when   the condition child node `(n->u[0].p)`  is traversed for the first time, but not when the node is traversed in  the `do{}while` loop. Based on the code, I believe any test_cmd returning false the third time or later will also cause `rc -e` to exit, but I have not tested it.
Here is the relevant code in `walk.c:walk()`:
```
        cond = TRUE;
        if (!walk(n->u[0].p, TRUE)) { /* prevent spurious breaks inside test */
            cond = oldcond;
            break;
        }
        . . .
        do {
            . . .
            cond = oldcond;
            . . .
            walk(n->u[1].p, TRUE);
            testtrue = walk(n->u[0].p, TRUE);
            . . . 
            cond = TRUE;
        } while (testtrue);
        cond = oldcond;
        . . .
```

**Comment by TobyGoodwin** [comment]
Thanks for the report, that certainly looks like a bug. I'm on holiday at the moment, but will look at this properly next week.
