### ISSUE TITLE
trip.rc fails on MacOS : /bin/pwd uses $PWD to print logical name

### ISSUE THREAD

**Issue by borkovic** [rakitzis/rc#36]
On MacOS /tmp is a soft link to /private/tmp.
In the code below '/bin/pwd' prints logical path if env variable $PWD is set and can be related to the current directory. "sh -c 'cd /tmp; /bin/pwd'" prints the logical name /tmp, but "/bin/pwd" prints physical name /private/tmp.
One fix would be to change every '/bin/pwd' to '/bin/pwd -P'.

In trip.rc:
```
pwd=`/bin/pwd cdpath=/ { # some local assignments
	home=/tmp cd
	if (!~ `/bin/pwd `{sh -c 'cd /tmp; /bin/pwd'})
		fail could not cd to '$home'

	cdpath=/ cd tmp
	if (!~ `/bin/pwd `{sh -c 'cd /tmp; /bin/pwd'})
		fail could not cd to /tmp

	cd $pwd
	if (!~ `/bin/pwd `{sh -c 'cd $pwd; /bin/pwd'})
		fail could not cd to current directory!
}
```

**Comment by TobyGoodwin** [comment]
Thanks, I've switched to `/bin/pwd -P` as you suggest in 1952b15
Can you check that solves it for you?

**Comment by borkovic** [comment]
Yes, it works for me.

**Comment by TobyGoodwin** [comment]
awesome :)
thanks... as always!
