### ISSUE TITLE
Unicode broken when set as login shell

### ISSUE THREAD

**Issue by byouki-onna** [rakitzis/rc#39]
if I change my login shell to rc, it wont display many unicode characters when I next login. (the usual arrangement is just 'exec rc' at the bottom of the login shells rcfile). Japanese characters just don't render at all and the unicode in my prompt renders as underscores. 
prompt=('჻' '')
fn prompt {
printf 「$HOSTNAME☼$USER」;
date +「%I:%M' '%p」|tr -d '\n';
PWD=`pwd
printf 「$PWD」|sed 's:'$HOME':~:';
printf \n
}
Is the prompt, if you'd like to try it specifically. I omitted the colors so this wont require posting the long list of color variables, I dont think they matter here. Theres also a line at the top of .rcrc, '/bin/echo/ -ne \033%G', copied from my .mkshrc which I dont know what  exactly its for, but I dont think it matters here either.
This is on Void linux.

**Comment by byouki-onna** [comment]
in retrospect this was obviously a locale problem and I actually figured out how to fix it('locale' printed everything with backslash-escaped double quotes for some reason, just putting everything unquoted and LC_ALL='' in .rcrc fixed it).  Itd probably be reasonable to say this isnt rc's problem and close it, I'll leave it open in case you don't think so.

**Comment by TobyGoodwin** [comment]
umm, yeah, SEP (Somebody Else's Problem)
