### ISSUE TITLE
Incorrect status value with pipes and -e flag

### ISSUE THREAD

**Issue by hallik** [rakitzis/rc#40]
Hi,

I thing there is an incorrect status value returned when
pipe is used in command and rc is executed with -e flag:

```
; rc -c 'false' ; echo $status                # OK
1
; rc -c 'false | false' ; echo $status        # OK
1
; rc -e -c 'false' ; echo $status             # OK
1
; rc -e -c 'false | false' ; echo $status     # INCORRECT STATUS
0
```
The same behavior appear in backquote substitution.

Tested on latest git commit 7dc3033.

-- Hallik

**Comment by muennich** [comment]
Just a reminder: this issue is resolved in master and can be closed.

**Comment by TobyGoodwin** [comment]
Just so. Thanks!
