### ISSUE TITLE
add code of conduct

### ISSUE THREAD

**Issue by TobyGoodwin** [rakitzis/rc#46]
Clicking around github, I came across their suggestion that we should add a [code of conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html) to the project.

It's hard to imagine this little community reaching the stage where we need such a thing, but on the other hand better to have something concrete in place beforehand if we ever do. So I'm in favour.

One thing we would need is an email address for the project, and it seems like it really needs to expand to at least a few different people to make any sense. I can easily host such a thing at one of my myriad domains :smiley:

Would anyone like to be on it? You'll need to let me know your email address: either add it as a comment here, or email me toby@paccrat.org

**Comment by slump64** [comment]
Harrasment on the internet doesn't exist.
We don't need another COC, programmers are not bounded to any believes, they write their code separetely from the political agenda.

**Comment by Redfoxmoon3** [comment]
Even though I have no ties to this project, I'd like to weigh in and say you shouldn't add something like a CoC, illegal things are already illegal, "code of conducts" only do one thing and that is discourage interaction with projects as they force people have to step on egg shells at all times. TL;DR. thought police, bad.
