### ISSUE TITLE
missing INSTALL document

### ISSUE THREAD

**Issue by malikbenkirane** [rakitzis/rc#52]
Hello,

`INSTALL` as mentioned [here][1] is missing.

I never used autotools before and it looks like knowledge from this toolkit is required to build rc (I see Makefile.am and configure.ac files). Could you please provide some help/doc/build instructions ?

Sincerely,

[1]: https://github.com/rakitzis/rc/blob/9c6211258c808637d6a71430b191841f0c50ed25/README#L21

**Comment by TobyGoodwin** [comment]
Assuming you're building from github, all you should need to get going is

    sh bootstrap

Note that this will *create* `INSTALL` with the generic instructions. Then run the usual commands, such as

    sh configure --with-edit=readline
    make
    make test

Obviously this needs to be written down somewhere! Perhaps `README.md`

**Comment by malikbenkirane** [comment]
Thank you for the instructions I propose the following patch for the README
```
diff --git a/README b/README
index 004d5e2..32cf793 100644
--- a/README
+++ b/README
@@ -18,6 +18,11 @@ See COPYING for copying information. All files are
 
    Copyright 1991, 1999, 2001-2003, 2014, 2015 Byron Rakitzis.
 
+If you build this from the github repository, run `sh bootstrap`, it
+generates INSTALL instructions
+(alternatively `autoreconf --force --install` is enough to make all the
+tools required for rc build and installation)
+
 See INSTALL for build and installation information.
 
 The current maintainer is Toby Goodwin[1]. Please contact him with any
```

**Comment by xyb3rt** [comment]
I've added some install instruction to the README.
