### ISSUE TITLE
Should ifs split by strings?

### ISSUE THREAD

**Issue by Nomarian** [rakitzis/rc#55]
This is more of a feature request and would maybe break behaviour but considering ifs is a list, it should probably behave in a manner of ifs=($nl^$nl $ifs(1)) that is, split by 2 newline characters (a string) and because its a list to also split by all other elements in the ifs list

**Comment by stephane-chazelas** [comment]
That would make sense (and would also work around the fact that this `rc` doesn't support multi-byte characters), but that would break backward compatibility. I suppose some existing scripts use things like `ifs = ',: '`.

**Comment by khwerz** [comment]
well, brc already has `` $IFS {} and $^, which is unsupported in 9rc.

**Comment by xyb3rt** [comment]
I think we should definitely not change the behaviour of `$ifs`. What's your opinion on this, @rakitzis?

**Comment by rakitzis** [comment]
I'll close this. Let's leave ifs alone.
