### ISSUE TITLE
fix exponential-time globbing "bug"?

### ISSUE THREAD

**Issue by rakitzis** [rakitzis/rc#57]
Saw this paper by rsc not too long ago, was wondering if we should address this in rc. The fix should be minor but will need thorough testing.

https://research.swtch.com/glob

**Comment by borkovic** [comment]
https://github.com/muennich/rc/commit/1263ab60d5bf5612d273b80e87a430b9e0a75afd
Bert did it some time ago.

**Comment by rakitzis** [comment]
Where have I been!?

**Comment by borkovic** [comment]
I don't think it has been merged though.

**Comment by rakitzis** [comment]
Ah, well, ok so I'm not completely lost. Would be nice to have this commit.

**Comment by borkovic** [comment]
[Pull request](https://github.com/rakitzis/rc/pull/58)   
It is not hard to come up with test params that will rather robustly distinguish between the slow and the fast version, but that may slow down trip.rc.

**Comment by xyb3rt** [comment]
Done.
