### ISSUE TITLE
Inconsistent exit behaviour

### ISSUE THREAD

**Issue by fijal-void** [rakitzis/rc#66]
`; /bin/rc ./test-exit
still alive
; /usr/lib/plan9/bin/rc ./test-exit
;
; cat test-exit
#!/bin/rc
fn foo { exit 1 }

foo >/dev/null
echo 'still alive'
;
`
plan9port's rc behaves as expected. Without redirections exits.
Looks like the same problem as #62

**Comment by xyb3rt** [comment]
This is indeed a duplicate of #62. Closing.
