### ISSUE TITLE
Uninsulated subshell when you return

### ISSUE THREAD

**Issue by Nomarian** [rakitzis/rc#68]
```
fn isdir { @{ cd $^*;return $status } }
isdir /
```

will set directory to / instead of being insulated from the command

Not only that, but when you return, it leaves you inside the subshell.

**Comment by rakitzis** [comment]
Crazy edge case. I will look at this when I get a chance.

**Comment by borkovic** [comment]
It seems that this would not happen without the `return` statement inside `fn/@` -- is that correct?

**Comment by Nomarian** [comment]
Well, yeah, I've never used 9rc seriously but since it doesn't have return, you have to use exit. this makes you write the code correctly

```
fn isdir { @{ cd $^* >[2] /dev/null ;exit $status } }
```

Funnily enough, I think this might be a useful feature. create a subshell in a function and control it with other functions. its kind of dangerous but, might be nice.

**Comment by xyb3rt** [comment]
```
fn foo {
    echo xxx
    return >/dev/null
    echo yyy
}
foo
xxx
^D
yyy
```
This leaves you in the subshell created for the redirection. Hitting `Ctrl-D` exits it and the parent shell continues executing the function.

**Comment by rakitzis** [comment]
This is an unintended side-effect of the strategy described in #62 . Best to keep this in mind while designing a fix.
