### ISSUE TITLE
Tab completion causes crash.

### ISSUE THREAD

**Issue by birchb1024** [rakitzis/rc#75]
Tab completion causes crash. 

### How to reproduce

1. start rc
2. hit the Tab key

```
~ $ rc
; free(): double free detected in tcache 2
Aborted
```

### Environment

* Debian GNU/Linux 11 (bullseye)"
* package 'rc' 1.7.4

```
; echo $version
1.7.4 $Release: @(#)rc 1.7.4 (git description unavailable) $
; apt list rc
Listing... Done
rc/stable,now 1.7.4+97.gceb59bb-4 amd64 [installed]
```

**Comment by RamKromberg** [comment]
I can't reproduce this with the current github master on [Nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/shells/rc/default.nix).

It looks like the [Debian package](https://packages.debian.org/bullseye/rc) is [a few years behind upstream](https://salsa.debian.org/debian/rc/-/commits/master) and is using an [out-of-tree patch](https://sources.debian.org/patches/rc/1.7.4+97.gceb59bb-4/0005-Fix-uninitialized-variable-error.patch/) [that was rejected](https://github.com/rakitzis/rc/pull/56) over what sounds like a similar issue.

**Comment by bernhardu** [comment]
I came across this downstream [Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1004645) and found
that the mentioned out-of-tree patch might do the `efree(full);` twice.
I proposed there a fix by setting `full` to NULL after the first `efree` call.

**Comment by xyb3rt** [comment]
The bug was caused and fixed in Debian's patch.
