### ISSUE TITLE
Can't overwrite commands

### ISSUE THREAD

**Issue by nnzv** [rakitzis/rc#78]
### Description

Set a command as function will break current session. No logs, it's just like calling `exit`.

### Reproduce

1. Declare `fn ls { ls -FC $* }`
2. Execute `ls`

### Expected behavior

Overwrite the command itself, but adding parameters.

### Environment 

OS: Gentoo Linux
Version: rc-1.7.4-r2

**Comment by entity0xfe** [comment]
Thats because you call your self declared function within it self, resulting in a loop. Declare the inner `ls` with  full path or as 
```
fn ls { `{which ls} -FC $* }
```

**Comment by nnzv** [comment]
Oh, true. But should we call it a loop? Thank you, though.
