### ISSUE TITLE
fns are not exported... inconsistently

### ISSUE THREAD

**Issue by euclaise** [rakitzis/rc#79]
I noticed that this version of rc doesn't export functions like the Plan 9 (and p9p) version does.

### Example
a.rc:
```
fn myfn {
    echo hi
}
rc ./b.rc
```

b.rc:
```
myfn
```

### Result (vs plan9port for comparison)
```
euclaise@thinkpad ~ $ rc ./a.rc
rc: cannot find `myfn'
euclaise@thinkpad ~ 1 $ 9 rc ./a.rc
hi
```
9front's rc yields the same result as plan9port's

**Comment by euclaise** [comment]
Oh, interesting.

After further testing (repeating it in bash and itself), it seems to occur specifically when ran from the `yash` shell.

**Comment by rakitzis** [comment]
That’s really weird. If you can narrow it down further I’d be grateful for details on this issue.

**Comment by euclaise** [comment]
I'll try when I have some more time

**Comment by euclaise** [comment]
Things get even more confusing...

Same shell, two different terminal windows:
![image](https://user-images.githubusercontent.com/25946465/206807148-645a9036-58ca-4193-9200-4d8b88319149.png)

**Comment by rakitzis** [comment]
I can't explain what is going on but I wonder if you are running one shell with another shell's functions in its environment. Plan9port and my rc have undoubtedly different serializations of shell functions in the environment.

A side note: when you invoke `bash rc` you are instructing bash to run the rc binary as a shell script. That can't and shouldn't work.

**Comment by euclaise** [comment]
> I can't explain what is going on but I wonder if you are running one shell with another shell's functions in its environment. Plan9port and my rc have undoubtedly different serializations of shell functions in the environment.

Unless I accidentally added another level of nesting, both of those should have been running from a single `yash` instance under the default environment from xfce4-terminal

> A side note: when you invoke bash rc you are instructing bash to run the rc binary as a shell script. That can't and shouldn't work.

Oh, duh, I feel silly now :b

**Comment by euclaise** [comment]
Oh, it seems it may be an incompatibility between rcs

```
euclaise@thinkpad ~ 1 $ cat a.rc
fn myfn {
    echo hello
}
rc ./b.rc
euclaise@thinkpad ~ $ cat a.9rc
fn myfn {
    echo hello
}
/usr/lib/plan9/bin/rc ./b.rc
euclaise@thinkpad ~ $ cat b.rc
myfn
euclaise@thinkpad ~ $ rc ./a.rc
hello
euclaise@thinkpad ~ $ 9 rc ./a.rc
hello
euclaise@thinkpad ~ $ /usr/lib/plan9/bin/rc ./a.rc
rc: cannot find `myfn'
euclaise@thinkpad ~ 1 $ 9 rc ./a.9rc
hello
euclaise@thinkpad ~ $ /usr/lib/plan9/bin/rc ./a.9rc
hello
euclaise@thinkpad ~ $ 
```
