### ISSUE TITLE
`if not` affected by vacuous `if (false)`

### ISSUE THREAD

**Issue by borkovic** [rakitzis/rc#82]
`if not` behaves differently when vacuous `if (false)` is added.

Current master commit:
```
$ g br
* master 8ca9ab1 [origin/master] Merge pull request #72 from rakitzis/travis
```

Without `if (false)`:
```
$ cat F4
L=xx
if (true) {
}
if not L=($L  a3)
whatis L
```

```
$ rc F4
L=xx
```

With `if (false)`"
```
$ cat F5
if (false) {
}
L=xx
if (true) {
}
if not L=($L  a3)
whatis L
```

```
$ rc F5
L=(xx a3)
```

I discovered it when I added `if (...) { ... }` to my `.rcrc` file and found that `trip.rc` fails in the same manner.   
I was calling rc with the `-l` flag.

Should `if (...)` be visible across files? I did not expect it to be.

**Comment by borkovic** [comment]
Does a `if not` statement have to follow an `if` statement immediately?

**Comment by rakitzis** [comment]
Hi Drazen, I'm afraid the `if not` syntax was retrofitted late in rc's life by a maintainer who is no longer associated with the project. When I have the time to clean up the loose ends I would prefer to remove this syntax entirely; as far as I am concerned it was added experimentally. At the moment I have little spare time to devote to rc maintenance.

**Comment by xyb3rt** [comment]
I've removed the `if not` syntax, so this is no longer an issue.
